/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef WatRaft_CONSTANTS_H
#define WatRaft_CONSTANTS_H

#include "WatRaft_types.h"

namespace WatRaft {

class WatRaftConstants {
 public:
  WatRaftConstants();

};

extern const WatRaftConstants g_WatRaft_constants;

} // namespace

#endif
