// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "WatRaft.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::WatRaft;

class WatRaftHandler : virtual public WatRaftIf {
 public:
  WatRaftHandler() {
    // Your initialization goes here
  }

  void get(std::string& _return, const std::string& key) {
    // Your implementation goes here
    printf("get\n");
  }

  void put(const std::string& key, const std::string& val) {
    // Your implementation goes here
    printf("put\n");
  }

  void append_entries(AEResult& _return, const int32_t term, const int32_t leader_id, const int32_t prev_log_index, const int32_t prev_log_term, const std::vector<Entry> & entries, const int32_t leader_commit_index) {
    // Your implementation goes here
    printf("append_entries\n");
  }

  void request_vote(RVResult& _return, const int32_t term, const int32_t candidate_id, const int32_t last_log_index, const int32_t last_log_term) {
    // Your implementation goes here
    printf("request_vote\n");
  }

  void debug_echo(std::string& _return, const std::string& msg) {
    // Your implementation goes here
    printf("debug_echo\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<WatRaftHandler> handler(new WatRaftHandler());
  shared_ptr<TProcessor> processor(new WatRaftProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

